import type { Metadata } from "next";
import "./globals.css";
import GlobalStyles from "@/styles/GlobalStyles";
import Providers from "./Providers";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <React.StrictMode>
          <Providers>
            <GlobalStyles />
            {children}
          </Providers>
        </React.StrictMode>
      </body>
    </html>
  );
}
